version: "3.7"

services:
  payment-gateway-api:
    image: ghcr.io/pokedex-gamba/payment-gateway-api:latest
    ports:
      - "8894:80"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/payment_history
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - MONEY_MANAGER_API_URL=http://host.docker.internal:8893
    depends_on:
      - db
    volumes:
      - ./decoding_key:/decoding_key
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8.0
    build: ./database
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: payment_history
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: